'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'app.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'styles.css'), 'utf8');
const workbenchSection = appJs.split('function SettingsPanel')[0];
const settingsSection = appJs.split('function SettingsPanel')[1] || '';

test('renderer boots from a single React root instead of the legacy multi-view shell', () => {
  assert.match(indexHtml, /<div id="root"><\/div>/);
  assert.match(indexHtml, /<script src="\.\/app\.js"><\/script>/);
  assert.doesNotMatch(indexHtml, /class="nav-btn"/);
  assert.doesNotMatch(indexHtml, /class="view"/);
  assert.doesNotMatch(indexHtml, /id="view-dashboard"/);
});

test('workbench shell exposes the chat-first layout with settings sub-tabs', () => {
  assert.match(appJs, /data-workbench-shell/);
  assert.match(appJs, /data-route-tab/);
  assert.match(appJs, /"workbench"/);
  assert.match(appJs, /"monitor"/);
  assert.match(appJs, /"settings"/);
  assert.match(appJs, /"inbox"/);
  assert.match(appJs, /Handbook/);
  assert.match(appJs, /data-settings-tab/);
  assert.match(appJs, /"ai"/);
  assert.match(appJs, /"labs"/);
  assert.match(appJs, /"learning"/);
  assert.match(appJs, /Storage & Diagnostics/);
  assert.match(appJs, /Queued automations/);
  assert.match(appJs, /Automation jobs/);
  assert.match(appJs, /Create self-host lab/);
  assert.match(appJs, /Import selected model/);
  assert.match(appJs, /Talk to the engine like a teammate/);
  assert.match(appJs, /Let's build/);
  assert.match(appJs, /chat-activity-strip/);
  assert.match(appJs, /right-rail-toggle/);
  assert.match(appJs, /manager-drawer/);
  assert.match(appJs, /Check for updates/);
  assert.match(appJs, /Install update|Open staged installer/);
  assert.match(appJs, /checkBinaryUpdates/);
  assert.match(appJs, /downloadBinaryUpdate/);
  assert.match(appJs, /installBinaryUpdate/);
  assert.match(appJs, /props\.onUpdateSetting\("chatMode", event\.target\.value\)/);
  assert.match(appJs, /Manager/);
  assert.match(appJs, /Worker/);
  assert.match(appJs, /Mode/);
  assert.match(appJs, /props\.onUpdateSetting\("aiRemoteModel"/);
  assert.match(appJs, /props\.onUpdateSetting\("trainingOllamaModel"/);
  assert.match(appJs, /Plan the next safe coding task/);
  assert.match(appJs, /Review the current repo and tell me what needs fixing first/);
  assert.match(appJs, /Set up the coding model and verify the engine is ready/);
  assert.match(appJs, /Local model MVP ladder/);
  assert.match(appJs, /Capability unlock ladder/);
  assert.match(appJs, /supervised engine loop/);
  assert.match(appJs, /dedupeInboxItems/);
  assert.match(appJs, /deriveInboxDedupeKey/);
  assert.match(appJs, /const scheduleRefresh = \(0, import_react2\.useEffectEvent\)/);
  assert.doesNotMatch(appJs, /const \[managerPanelOpen, setManagerPanelOpen\]/);
  assert.match(appJs, /chatTransparencyLevel/);
  assert.match(appJs, /MONITOR_TABS = \["overview", "runs", "learning", "promotions", "debug"\]/);
  assert.match(appJs, /data-panel/);
  assert.match(settingsSection, /Automation jobs/);
  assert.match(settingsSection, /Create self-host lab/);
  assert.match(settingsSection, /Storage & Diagnostics/);
  assert.match(settingsSection, /Import selected model/);
  assert.match(settingsSection, /Inspector mode/);
  assert.match(settingsSection, /Composer height/);
  assert.match(settingsSection, /Install companion/);
  assert.match(settingsSection, /Companion install/);
  assert.match(settingsSection, /Auto-queue bounded next task after the run settles/);
  assert.match(settingsSection, /Auto-run queued next task when safe/);
  assert.match(settingsSection, /Remote API key slot/);
  assert.match(settingsSection, /Remote API key name/);
  assert.match(settingsSection, /window\.gosAgent\.setSecret/);
  assert.doesNotMatch(settingsSection, /window\.prompt/);
  assert.match(settingsSection, /Provider API key/);
  assert.match(settingsSection, /type: "password"/);
  assert.match(settingsSection, /API keys/);
  assert.match(settingsSection, /Hugging Face Hub token/);
  assert.match(settingsSection, /Save .*key/);
  assert.match(settingsSection, /data-api-key-modal/);
  assert.match(workbenchSection, /const scheduleRefresh = \(0, import_react2\.useEffectEvent\)/);
});

test('shell keeps model, labs, learning, and file-edit actions connected to preload APIs', () => {
  assert.match(appJs, /window\.gosAgent\.chatMessage/);
  assert.match(appJs, /window\.gosAgent\.pickChatAttachments/);
  assert.match(appJs, /window\.gosAgent\.runLabRecipe/);
  assert.match(appJs, /window\.gosAgent\.runBenchmark/);
  assert.match(appJs, /window\.gosAgent\.runMonitorAcceptance/);
  assert.match(appJs, /window\.gosAgent\.setMonitorSafeMode/);
  assert.match(appJs, /window\.gosAgent\.createCandidate/);
  assert.match(appJs, /window\.gosAgent\.promoteCandidate/);
  assert.match(appJs, /window\.gosAgent\.exportMonitorDebugBundle/);
  assert.match(appJs, /window\.gosAgent\.bootstrap\(/);
  assert.match(appJs, /window\.gosAgent\.bootstrapLite\(/);
  assert.match(appJs, /window\.gosAgent\.openLocation/);
  assert.match(appJs, /path: handbookPath/);
  assert.match(appJs, /window\.gosAgent\.updateSettings/);
  assert.match(appJs, /props\.onUpdateSetting\("chatMode"/);
  assert.match(appJs, /props\.onUpdateSetting\("aiRemoteModel"/);
  assert.match(appJs, /props\.onUpdateSetting\("trainingOllamaModel"/);
  assert.match(appJs, /onOpenMonitorTab/);
  assert.match(appJs, /safetyLevel/);
  assert.match(appJs, /window\.gosAgent\.getAiStatus/);
  assert.match(appJs, /window\.gosAgent\.listTools/);
  assert.match(appJs, /window\.gosAgent\.saveReviewFile/);
  assert.match(appJs, /window\.gosAgent\.setReviewDecision/);
  assert.match(appJs, /window\.gosAgent\.openInVsCode/);
  assert.match(appJs, /window\.gosAgent\.bootstrapWorkspaceVsCode/);
  assert.match(appJs, /window\.gosAgent\.exportLearningChanges/);
  assert.match(appJs, /window\.gosAgent\.createTask/);
  assert.match(appJs, /window\.gosAgent\.recordOperatorFeedback/);
  assert.match(appJs, /window\.gosAgent\.queueFollowupRecipe/);
});

test('chat shell keeps the selector-driven human-first controls and desktop git workspace visible', () => {
  assert.match(appJs, /chatModes = \["auto", "ask", "plan", "edit", "agent"\]/);
  assert.match(appJs, /chat-activity-strip/);
  assert.match(appJs, /manager-drawer/);
  assert.match(appJs, /modeRouteSummary\[chatMode\]/);
  assert.match(appJs, /composer-selector-row/);
  assert.match(appJs, /effective \${effectiveChatMode}/);
  assert.match(appJs, /Auto-run queued tasks/);
  assert.match(appJs, /Use auto manager/);
  assert.match(appJs, /Run hygiene/);
  assert.match(appJs, /reportRendererError/);
  assert.match(appJs, /branchLabel/);
  assert.match(appJs, /safetyLabel/);
  assert.match(appJs, /openModule === "monitor"/);
  assert.match(stylesCss, /\.chat-mode-bar/);
  assert.match(stylesCss, /\.composer-selector-row/);
  assert.match(stylesCss, /\.selector-chip/);
  assert.match(stylesCss, /\.chat-compact-strip/);
  assert.match(stylesCss, /\.chat-activity-strip/);
  assert.match(stylesCss, /\.manager-drawer/);
});

test('styles define the codex-style workbench shell and theme system', () => {
  assert.match(stylesCss, /\.workbench-shell \{/);
  assert.match(stylesCss, /\.left-rail \{/);
  assert.match(stylesCss, /\.center-grid \{/);
  assert.match(stylesCss, /\.chat-log \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-active \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-message \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-alert \{/);
  assert.match(stylesCss, /\.safety-banner \{/);
  assert.match(stylesCss, /\.workbench-status-strip \{/);
  assert.match(stylesCss, /position:\s*sticky;/);
  assert.match(stylesCss, /\.chat-mode-bar \{/);
  assert.match(stylesCss, /\.composer-selector-row \{/);
  assert.match(stylesCss, /\.selector-chip \{/);
  assert.match(stylesCss, /color-scheme:\s*dark;/);
  assert.match(stylesCss, /\.selector-chip select option \{/);
  assert.match(stylesCss, /\.chat-compact-strip \{/);
  assert.match(stylesCss, /overflow:\s*auto;/);
  assert.match(stylesCss, /\.settings-tabs \{/);
  assert.match(stylesCss, /\.attachment-chip \{/);
  assert.match(stylesCss, /\.monitor-panel \{/);
  assert.match(stylesCss, /\.code-editor,/);
  assert.match(stylesCss, /\.event-stream \{/);
  assert.match(stylesCss, /body\[data-theme="obsidian"\]/);
  assert.match(stylesCss, /body\[data-theme="codex"\]/);
  assert.match(stylesCss, /\.modal-scrim \{/);
  assert.match(stylesCss, /\.settings-modal \{/);
  assert.match(stylesCss, /\.api-key-modal-layout \{/);
});
