'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'app.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'styles.css'), 'utf8');
const workbenchSection = appJs.split('function SettingsPanel')[0];
const settingsSection = appJs.split('function SettingsPanel')[1] || '';

test('renderer boots from a single React root instead of the legacy multi-view shell', () => {
  assert.match(indexHtml, /<div id="root"><\/div>/);
  assert.match(indexHtml, /<script src="\.\/app\.js"><\/script>/);
  assert.doesNotMatch(indexHtml, /class="nav-btn"/);
  assert.doesNotMatch(indexHtml, /class="view"/);
  assert.doesNotMatch(indexHtml, /id="view-dashboard"/);
});

test('workbench shell exposes the chat-first layout with settings sub-tabs', () => {
  assert.match(appJs, /data-workbench-shell/);
  assert.match(appJs, /data-route-tab/);
  assert.match(appJs, /"workbench"/);
  assert.match(appJs, /"monitor"/);
  assert.match(appJs, /"settings"/);
  assert.match(appJs, /"inbox"/);
  assert.match(appJs, /data-settings-tab/);
  assert.match(appJs, /One place to watch the engine, learning loop, and promotion rings/);
  assert.match(appJs, /Loading control room/);
  assert.match(appJs, /5-phase MVP/);
  assert.match(appJs, /5-phase MVP readiness/);
  assert.match(appJs, /Current phase/);
  assert.match(appJs, /Phase gate/);
  assert.match(appJs, /Phase proof/);
  assert.match(appJs, /Next phase-safe action/);
  assert.match(appJs, /Self-host expansion/);
  assert.match(appJs, /Self-host expansion outcome/);
  assert.match(appJs, /Self-host expansion next step/);
  assert.match(appJs, /Phase closeout/);
  assert.match(appJs, /Closeout blockers/);
  assert.match(appJs, /Next phase preview/);
  assert.match(appJs, /Internal audit/);
  assert.match(appJs, /Phase scorecard/);
  assert.match(appJs, /Run acceptance/);
  assert.match(appJs, /Latest smoke/);
  assert.match(appJs, /Next day gate/);
  assert.match(appJs, /Blocking checks/);
  assert.match(appJs, /Pause risky work/);
  assert.match(appJs, /Restore this backup/);
  assert.match(appJs, /Selector catalog/);
  assert.match(appJs, /Resolved bridge command/);
  assert.match(appJs, /"ai"/);
  assert.match(appJs, /"labs"/);
  assert.match(appJs, /"learning"/);
  assert.match(appJs, /Storage & Diagnostics/);
  assert.match(appJs, /Queued automations/);
  assert.match(appJs, /Automation jobs/);
  assert.match(appJs, /Create self-host lab/);
  assert.match(appJs, /Import selected model/);
  assert.match(appJs, /Ask the coding model what to build, fix, review, or explain\./);
  assert.match(appJs, /Let's build/);
  assert.match(appJs, /Dev-engine control loop/);
  assert.match(appJs, /Current objective/);
  assert.match(appJs, /Route and stage/);
  assert.match(appJs, /Failure class/);
  assert.match(appJs, /Checkpoint/);
  assert.match(appJs, /Recovery and review/);
  assert.match(appJs, /Recovery ladder/);
  assert.match(appJs, /Review bundle/);
  assert.match(appJs, /Review verdict/);
  assert.match(appJs, /Review reason/);
  assert.match(appJs, /How to fix/);
  assert.match(appJs, /Learned guidance/);
  assert.match(appJs, /Phase focus/);
  assert.match(appJs, /Learned path/);
  assert.match(appJs, /Self-host proof/);
  assert.match(appJs, /Self-host next step/);
  assert.match(appJs, /Top reject pattern/);
  assert.match(appJs, /Preferred response/);
  assert.match(appJs, /Change summary/);
  assert.match(appJs, /Interrupt request/);
  assert.match(appJs, /Workbench artifacts/);
  assert.match(appJs, /Continue run/);
  assert.match(appJs, /Retry with research/);
  assert.match(appJs, /Repair loop/);
  assert.match(appJs, /Run next safe action/);
  assert.match(appJs, /Queue next task/);
  assert.match(appJs, /Pinned run tasks/);
  assert.match(appJs, /Pinned profiles/);
  assert.match(appJs, /data-run-task-pins/);
  assert.match(appJs, /data-profile-pins/);
  assert.match(appJs, /workbench-pinned-bar.*is-compact/);
  assert.match(appJs, /Open trace/);
  assert.match(appJs, /Open sandbox/);
  assert.match(appJs, /Review interrupt/);
  assert.match(appJs, /Rollback last pass/);
  assert.match(appJs, /Engine helper/);
  assert.match(appJs, /Next safe action/);
  assert.match(appJs, /Chat view/);
  assert.match(appJs, /Focus chat/);
  assert.match(appJs, /Control room/);
  assert.match(appJs, /data-chat-primary-strip/);
  assert.match(appJs, /workbench-run-strip/);
  assert.match(appJs, /Run supervised self-improvement/);
  assert.match(appJs, /Self-improvement proof/);
  assert.match(appJs, /Companion parity/);
  assert.match(appJs, /Chat settings/);
  assert.match(appJs, /data-workbench-mode/);
  assert.match(appJs, /data-workbench-mode-toggle/);
  assert.match(appJs, /data-dev-engine-loop/);
  assert.match(appJs, /Keep chat clean and move the system controls here/);
  assert.match(appJs, /Reject and fix patterns/);
  assert.match(appJs, /Reusable fix guidance/);
  assert.match(appJs, /window\.setTimeout\(\(\) => \{\s*void refreshMonitor\(\);/);
  assert.match(appJs, /monitorLoadingMessage/);
  assert.match(appJs, /data-panel/);
  assert.match(settingsSection, /Automation jobs/);
  assert.match(settingsSection, /Create self-host lab/);
  assert.match(settingsSection, /Storage & Diagnostics/);
  assert.match(settingsSection, /Import selected model/);
  assert.match(settingsSection, /Workbench view/);
  assert.match(settingsSection, /Composer height/);
  assert.match(settingsSection, /Install companion/);
  assert.match(settingsSection, /Companion install/);
  assert.match(settingsSection, /Task-loop follow-ups/);
  assert.match(settingsSection, /Auto-queue bounded next task after the run settles/);
  assert.match(settingsSection, /Auto-run queued next task when safe/);
  assert.match(settingsSection, /Remote API key slot/);
  assert.doesNotMatch(settingsSection, /Remote API key name/);
  assert.match(settingsSection, /window\.gosAgent\.setSecret/);
  assert.doesNotMatch(settingsSection, /window\.prompt/);
  assert.match(settingsSection, /Provider API key/);
  assert.match(settingsSection, /type: "password"/);
  assert.match(settingsSection, /Save .* key/);
  assert.match(workbenchSection, /window\.setTimeout\(\(\) => \{\s*void refreshMonitor\(\);/);
});

test('shell keeps model, labs, learning, and file-edit actions connected to preload APIs', () => {
  assert.match(appJs, /window\.gosAgent\.chatMessage/);
  assert.match(appJs, /window\.gosAgent\.pickChatAttachments/);
  assert.match(appJs, /window\.gosAgent\.runLabRecipe/);
  assert.match(appJs, /window\.gosAgent\.runBenchmark/);
  assert.match(appJs, /window\.gosAgent\.runMonitorAcceptance/);
  assert.match(appJs, /window\.gosAgent\.setMonitorSafeMode/);
  assert.match(appJs, /window\.gosAgent\.createCandidate/);
  assert.match(appJs, /window\.gosAgent\.promoteCandidate/);
  assert.match(appJs, /window\.gosAgent\.exportMonitorDebugBundle/);
  assert.match(appJs, /window\.gosAgent\.getMonitorStatus/);
  assert.match(appJs, /window\.gosAgent\.executeTaskLoop/);
  assert.match(appJs, /window\.gosAgent\.retryTaskLoop/);
  assert.match(appJs, /window\.gosAgent\.repairTaskLoop/);
  assert.match(appJs, /window\.gosAgent\.openArtifactPath/);
  assert.match(appJs, /props\.onRunNextTaskLoopAction/);
  assert.match(appJs, /props\.onQueueNextTaskLoopFollowup/);
  assert.match(appJs, /window\.gosAgent\.queueTaskLoopNextActionFollowup/);
  assert.match(appJs, /window\.gosAgent\.selfImprove/);
  assert.match(appJs, /props\.onRunSupervisedSelfImprove/);
  assert.match(appJs, /nextAction\.command/);
  assert.match(appJs, /props\.onUpdateSetting\("chatWorkbenchMode"/);
  assert.match(appJs, /props\.onUpdateSetting\("chatComposerSize"/);
  assert.match(appJs, /monitorLoading/);
  assert.match(appJs, /busyTaskLoop/);
  assert.match(appJs, /safetyLevel/);
  assert.match(appJs, /window\.gosAgent\.getAiStatus/);
  assert.match(appJs, /window\.gosAgent\.listTools/);
  assert.match(appJs, /window\.gosAgent\.saveReviewFile/);
  assert.match(appJs, /window\.gosAgent\.setReviewDecision/);
  assert.match(appJs, /window\.gosAgent\.openInVsCode/);
  assert.match(appJs, /window\.gosAgent\.installWorkspaceVsCodeCompanion/);
  assert.match(appJs, /window\.gosAgent\.exportLearningChanges/);
  assert.match(appJs, /window\.gosAgent\.createTask/);
  assert.match(appJs, /window\.gosAgent\.recordOperatorFeedback/);
  assert.match(appJs, /window\.gosAgent\.queueFollowupRecipe/);
});

test('chat shell keeps the human-first mode bar and desktop git workspace visible', () => {
  assert.match(appJs, /data-route-tab": "git"/);
  assert.match(appJs, /data-chat-mode-bar/);
  assert.match(appJs, /\["ask", "Ask"\]/);
  assert.match(appJs, /\["plan", "Plan"\]/);
  assert.match(appJs, /\["edit", "Edit"\]/);
  assert.match(appJs, /\["agent", "Agent"\]/);
  assert.match(appJs, /"data-chat-mode-toggle": mode/);
  assert.match(appJs, /data-chat-git-summary/);
  assert.match(appJs, /Git: /);
  assert.match(appJs, /Desktop Git/);
  assert.match(appJs, /Commit staged/);
  assert.match(appJs, /Publish branch/);
  assert.match(appJs, /Create branch/);
  assert.match(appJs, /Switch branch/);
  assert.match(appJs, /Diff viewer/);
  assert.match(stylesCss, /\.chat-mode-bar/);
  assert.match(stylesCss, /\.workbench-git-summary/);
  assert.match(stylesCss, /\.git-diff-viewer/);
});

test('styles define the codex-style workbench shell and theme system', () => {
  assert.match(stylesCss, /\.workbench-shell \{/);
  assert.match(stylesCss, /\.left-rail \{/);
  assert.match(stylesCss, /\.center-grid \{/);
  assert.match(stylesCss, /\.chat-log \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-active \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-message \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-alert \{/);
  assert.match(stylesCss, /\.safety-banner \{/);
  assert.match(stylesCss, /\.workbench-status-strip \{/);
  assert.match(stylesCss, /\.workbench-layout-bar \{/);
  assert.match(stylesCss, /position:\s*sticky;/);
  assert.match(stylesCss, /\.workbench-layout-bar\.is-fresh-thread \{/);
  assert.match(stylesCss, /\.workbench-pinned-bar \{/);
  assert.match(stylesCss, /\.workbench-pinned-bar\.is-sticky \{/);
  assert.match(stylesCss, /\.workbench-pinned-bar\.is-compact \{/);
  assert.match(stylesCss, /\.pinned-task-card,/);
  assert.match(stylesCss, /\.pinned-profile-card \{/);
  assert.match(stylesCss, /\.workbench-run-strip \{/);
  assert.match(stylesCss, /\.run-strip-grid \{/);
  assert.match(stylesCss, /\.chat-home-main\.mode-focus \{/);
  assert.match(stylesCss, /\.chat-home-main\.mode-balanced,\s*\.chat-home-main\.mode-control-room \{/);
  assert.match(stylesCss, /overflow-y:\s*auto;/);
  assert.match(stylesCss, /\.chat-home-main\.mode-balanced \.chat-composer,\s*\.chat-home-main\.mode-control-room \.chat-composer \{/);
  assert.match(stylesCss, /position:\s*sticky;/);
  assert.match(stylesCss, /\.chat-home-main\.mode-balanced \.chat-log,\s*\.chat-home-main\.mode-control-room \.chat-log \{/);
  assert.match(stylesCss, /\.settings-tabs \{/);
  assert.match(stylesCss, /\.attachment-chip \{/);
  assert.match(stylesCss, /\.monitor-panel \{/);
  assert.match(stylesCss, /\.code-editor,/);
  assert.match(stylesCss, /\.event-stream \{/);
  assert.match(stylesCss, /body\[data-theme="obsidian"\]/);
  assert.match(stylesCss, /body\[data-theme="codex"\]/);
});
