'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'app.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'styles.css'), 'utf8');
const workbenchSection = appJs.split('function SettingsPanel')[0];
const settingsSection = appJs.split('function SettingsPanel')[1] || '';

test('renderer boots from a single React root instead of the legacy multi-view shell', () => {
  assert.match(indexHtml, /<div id="root"><\/div>/);
  assert.match(indexHtml, /<script src="\.\/app\.js"><\/script>/);
  assert.doesNotMatch(indexHtml, /class="nav-btn"/);
  assert.doesNotMatch(indexHtml, /class="view"/);
  assert.doesNotMatch(indexHtml, /id="view-dashboard"/);
});

test('workbench shell exposes the four-screen chat-first layout with nested workbench tools', () => {
  assert.match(appJs, /data-workbench-shell/);
  assert.match(appJs, /data-route-tab/);
  assert.match(appJs, /Chat/);
  assert.match(appJs, /Workbench/);
  assert.match(appJs, /Tune Pod/);
  assert.match(appJs, /"settings"/);
  assert.match(appJs, /"inbox"/);
  assert.match(appJs, /Handbook/);
  assert.doesNotMatch(appJs, /<strong>Agents<\/strong>|>Spark<|>Spaces</);
  assert.match(appJs, /data-settings-tab/);
  assert.match(appJs, /"ai"/);
  assert.match(appJs, /"tunepod"/);
  assert.match(appJs, /"labs"/);
  assert.match(appJs, /"learning"/);
  assert.match(appJs, /Storage and diagnostics roots/);
  assert.match(appJs, /Queued automations/);
  assert.match(appJs, /Automation jobs/);
  assert.match(appJs, /Create self-host lab/);
  assert.match(appJs, /Import selected model/);
  assert.match(appJs, /Use this rail only when you need extra detail/);
  assert.match(appJs, /Open Workbench IDE tools\./);
  assert.match(appJs, /Open workspace in VS Code/);
  assert.match(appJs, /Tool access exposed to the model/);
  assert.match(appJs, /Terminal lane/);
  assert.match(appJs, /Inspect active tasks, run history, changes, and proof/);
  assert.match(appJs, /See what fits this machine and what is ready now/);
  assert.match(appJs, /See what is ready now, saved, or still missing/);
  assert.match(appJs, /Welcome to GoSenderr/);
  assert.match(appJs, /Explain this repo/);
  assert.match(appJs, /Plan the next change/);
  assert.match(appJs, /chat-progress-indicator/);
  assert.match(appJs, /Thinking/);
  assert.match(appJs, /Starting the reply\u2026|One moment\u2026|Mapping the next step/);
  assert.match(appJs, /workbench-review-shell/);
  assert.match(appJs, /Validation checks/);
  assert.match(appJs, /Let's build/);
  assert.match(appJs, /chat-activity-strip/);
  assert.match(appJs, /right-rail-toggle/);
  assert.match(appJs, /manager-drawer/);
  assert.match(appJs, /Check for updates/);
  assert.match(appJs, /Install update|Open staged installer/);
  assert.match(appJs, /checkBinaryUpdates/);
  assert.match(appJs, /downloadBinaryUpdate/);
  assert.match(appJs, /installBinaryUpdate/);
  assert.match(appJs, /props\.onUpdateSetting\("chatMode", event\.target\.value\)/);
  assert.match(appJs, /Context/);
  assert.match(appJs, /Mode/);
  assert.match(appJs, /props\.onUpdateSetting\("aiRemoteModel"/);
  assert.match(appJs, /props\.onUpdateSetting\("trainingOllamaModel"/);
  assert.match(appJs, /Plan the next safe coding task/);
  assert.match(appJs, /Review the current repo and tell me what needs fixing first/);
  assert.match(appJs, /Open Tune Pod to finish model setup for this workspace/);
  assert.match(appJs, /Open Tune Pod to see which local models fit this PC/);
  assert.match(appJs, /Open Tune Pod to see what still needs setup for local coding/);
  assert.match(appJs, /Chat uses your current model setup/);
  assert.match(appJs, /Using the current workspace setup/);
  assert.match(appJs, /Advanced readiness ladder/);
  assert.match(appJs, /Advanced setup steps/);
  assert.match(appJs, /Manual model choices/);
  assert.match(appJs, /Task model choices/);
  assert.match(appJs, /Model choice/);
  assert.match(appJs, /Reset manual choices/);
  assert.match(appJs, /Let Chat choose the best help mode/);
  assert.match(appJs, /dedupeInboxItems/);
  assert.match(appJs, /deriveInboxDedupeKey/);
  assert.match(appJs, /const scheduleRefresh = \(0, import_react2\.useEffectEvent\)/);
  assert.doesNotMatch(appJs, /const \[managerPanelOpen, setManagerPanelOpen\]/);
  assert.match(appJs, /MONITOR_TABS = \["overview", "runs", "learning", "promotions", "debug", "ide"\]/);
  assert.match(appJs, /data-panel/);
  assert.match(settingsSection, /Automation jobs/);
  assert.match(settingsSection, /Create self-host lab/);
  assert.match(settingsSection, /diagnostics all live behind one modular settings surface/i);
  assert.match(settingsSection, /Import selected model/);
  assert.match(settingsSection, /Tune Pod/);
  assert.match(settingsSection, /Fits this PC/);
  assert.match(settingsSection, /Better on bigger hardware/);
  assert.match(appJs, /Open Tune Pod/);
  assert.match(appJs, /Workbench handoff/);
  assert.match(appJs, /Deep health, benchmarks, recovery, and debug exports moved to Workbench/);
  assert.match(settingsSection, /Inspector mode/);
  assert.match(settingsSection, /Composer height/);
  assert.match(settingsSection, /Install companion/);
  assert.match(settingsSection, /Companion install/);
  assert.match(settingsSection, /Auto-queue bounded next task after the run settles/);
  assert.match(settingsSection, /Auto-run queued next task when safe/);
  assert.match(settingsSection, /Remote API key slot/);
  assert.match(settingsSection, /Remote API key name/);
  assert.match(settingsSection, /window\.gosAgent\.setSecret/);
  assert.doesNotMatch(settingsSection, /window\.prompt/);
  assert.match(settingsSection, /Provider API key/);
  assert.match(settingsSection, /type: "password"/);
  assert.match(settingsSection, /API keys/);
  assert.match(settingsSection, /Hugging Face Hub token/);
  assert.match(settingsSection, /Save .*key/);
  assert.match(settingsSection, /data-api-key-modal/);
  assert.match(workbenchSection, /const scheduleRefresh = \(0, import_react2\.useEffectEvent\)/);
});

test('shell keeps model, labs, learning, and file-edit actions connected to preload APIs', () => {
  assert.match(appJs, /window\.gosAgent\.chatMessage/);
  assert.match(appJs, /window\.gosAgent\.onAssistantChatEvent/);
  assert.match(appJs, /renderChatMessageBody/);
  assert.match(appJs, /activeChatMessageId/);
  assert.match(appJs, /liveChatProgress/);
  assert.match(appJs, /requestId/);
  assert.match(appJs, /window\.gosAgent\.pickChatAttachments/);
  assert.match(appJs, /window\.gosAgent\.runLabRecipe/);
  assert.match(appJs, /window\.gosAgent\.runBenchmark/);
  assert.match(appJs, /window\.gosAgent\.runMonitorAcceptance/);
  assert.match(appJs, /window\.gosAgent\.setMonitorSafeMode/);
  assert.match(appJs, /window\.gosAgent\.createCandidate/);
  assert.match(appJs, /window\.gosAgent\.promoteCandidate/);
  assert.match(appJs, /window\.gosAgent\.exportMonitorDebugBundle/);
  assert.match(appJs, /window\.gosAgent\.bootstrap\(/);
  assert.match(appJs, /window\.gosAgent\.bootstrapLite\(/);
  assert.match(appJs, /window\.gosAgent\.openLocation/);
  assert.match(appJs, /path: handbookPath/);
  assert.match(appJs, /window\.gosAgent\.updateSettings/);
  assert.match(appJs, /props\.onUpdateSetting\("chatMode"/);
  assert.match(appJs, /props\.onUpdateSetting\("aiRemoteModel"/);
  assert.match(appJs, /props\.onUpdateSetting\("trainingOllamaModel"/);
  assert.match(appJs, /onOpenMonitorTab/);
  assert.match(appJs, /safetyLevel/);
  assert.match(appJs, /window\.gosAgent\.getAiStatus/);
  assert.match(appJs, /window\.gosAgent\.listTools/);
  assert.match(appJs, /window\.gosAgent\.installWorkspaceVsCodeCompanion/);
  assert.match(appJs, /window\.gosAgent\.openWorkspaceInVsCode/);
  assert.match(appJs, /window\.gosAgent\.saveReviewFile/);
  assert.match(appJs, /window\.gosAgent\.setReviewDecision/);
  assert.match(appJs, /window\.gosAgent\.openInVsCode/);
  assert.match(appJs, /window\.gosAgent\.bootstrapWorkspaceVsCode/);
  assert.match(appJs, /window\.gosAgent\.exportLearningChanges/);
  assert.match(appJs, /window\.gosAgent\.createTask/);
  assert.match(appJs, /window\.gosAgent\.recordOperatorFeedback/);
  assert.match(appJs, /window\.gosAgent\.queueFollowupRecipe/);
});

test('chat shell keeps the selector-driven human-first controls and desktop git workspace visible', () => {
  assert.match(appJs, /chatModes = \["auto", "ask", "plan", "edit", "agent"\]/);
  assert.match(appJs, /chat-activity-strip/);
  assert.match(appJs, /manager-drawer/);
  assert.match(appJs, /modeRouteSummary\[chatMode\]/);
  assert.match(appJs, /composer-selector-row/);
  assert.match(appJs, /Optional details/);
  assert.match(appJs, /Use this rail only when you need extra detail/);
  assert.match(appJs, /Check status/);
  assert.match(appJs, /reportRendererError/);
  assert.match(appJs, /branchLabel/);
  assert.match(appJs, /safetyLabel/);
  assert.match(appJs, /openModule === "monitor"/);
  assert.match(stylesCss, /\.chat-mode-bar/);
  assert.match(stylesCss, /\.composer-selector-row/);
  assert.match(stylesCss, /\.selector-chip/);
  assert.match(stylesCss, /\.chat-compact-strip/);
  assert.match(stylesCss, /\.chat-activity-strip/);
  assert.match(stylesCss, /\.manager-drawer/);
});

test('styles define the codex-style workbench shell and theme system', () => {
  assert.match(stylesCss, /\.workbench-shell \{/);
  assert.match(stylesCss, /\.left-rail \{/);
  assert.match(stylesCss, /\.center-grid \{/);
  assert.match(stylesCss, /\.chat-log \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-active \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-message \{/);
  assert.match(stylesCss, /\.chat-home-main\.signal-alert \{/);
  assert.match(stylesCss, /\.safety-banner \{/);
  assert.match(stylesCss, /\.workbench-status-strip \{/);
  assert.match(stylesCss, /position:\s*sticky;/);
  assert.match(stylesCss, /\.chat-mode-bar \{/);
  assert.match(stylesCss, /\.composer-selector-row \{/);
  assert.match(stylesCss, /\.selector-chip \{/);
  assert.match(stylesCss, /color-scheme:\s*dark;/);
  assert.match(stylesCss, /\.selector-chip select option \{/);
  assert.match(stylesCss, /\.chat-compact-strip \{/);
  assert.match(stylesCss, /overflow:\s*auto;/);
  assert.match(stylesCss, /\.settings-tabs \{/);
  assert.match(stylesCss, /\.attachment-chip \{/);
  assert.match(stylesCss, /\.monitor-panel \{/);
  assert.match(stylesCss, /\.ide-panel \{/);
  assert.match(stylesCss, /\.ide-hero \{/);
  assert.match(stylesCss, /\.ide-lane-grid/);
  assert.match(stylesCss, /\.chat-welcome-panel \{/);
  assert.match(stylesCss, /\.welcome-action-grid \{/);
  assert.match(stylesCss, /\.chat-message-body \{/);
  assert.match(stylesCss, /\.assistant-progress-card \{/);
  assert.match(stylesCss, /\.streaming-caret \{/);
  assert.match(stylesCss, /\.chat-code-block \{/);
  assert.match(stylesCss, /\.chat-inline-code \{/);
  assert.match(stylesCss, /\.chat-section-heading \{/);
  assert.match(stylesCss, /\.workbench-review-layout \{/);
  assert.match(stylesCss, /\.workbench-code-preview \{/);
  assert.match(stylesCss, /\.code-editor,/);
  assert.match(stylesCss, /\.event-stream \{/);
  assert.match(stylesCss, /body\[data-theme="obsidian"\]/);
  assert.match(stylesCss, /body\[data-theme="codex"\]/);
  assert.match(stylesCss, /\.modal-scrim \{/);
  assert.match(stylesCss, /\.settings-modal \{/);
  assert.match(stylesCss, /\.api-key-modal-layout \{/);
});
