from __future__ import annotations


REPO_MAP_SCHEMA_VERSION = 2
SKILLPACKS_SCHEMA_VERSION = 2

SELF_IMPROVEMENT_AUTONOMY_MODES = {"self", "self-improve", "self-only", "assistant"}
ASSISTANT_SELF_PATH_PREFIXES = (
    "backend/agent/",
    "backend/scripts/autopilot.py",
    "backend/scripts/solo_dev_assistant.py",
    "backend/scripts/solo_dev_assistant_runtime.py",
    "backend/tests/test_followup_bat_synthesis.py",
    "core/",
    "shared-runtime/",
    "shared-ui/",
    "host/",
    "renderer/",
    "renderer-src/",
    "scripts/",
    "tests/",
    "assets/",
    "HOW_TO_USE/",
    "main.js",
    "preload.js",
    "README.md",
    "desktop-learning-records.js",
    "runtime/backend/",
    "tools/gosenderr-desktop-agent/",
    "tools/vscode-dev-assistant-extension/",
    "docs/assistant_runs/",
    "docs/DEV_ASSISTANT",
)

IGNORED_RELATED_PATTERNS = (
    "__pycache__/",
    ".pyc",
    "node_modules/",
    "/build/",
    "/dist/",
    ".egg-info/",
)

FRONTEND_WORKSPACE_MAP = {
    "customer-app": "@gosenderr/customer-app",
    "senderr-app": "@gosenderr/senderr-app",
    "admin-app": "@gosenderr/admin-app",
    "business-app": "@gosenderr/business-app",
}

DOMAIN_PRIORITY_KEYWORDS = {
    "assistant_runtime": (
        "retry policy",
        "permission",
        "permissions",
        "approval",
        "approved",
        "deferred",
        "rejected",
        "write gate",
        "write-gate",
        "policy",
        "policy family",
        "downgrade",
        "confidence",
        "fingerprint",
        "validation",
        "repair",
        "orchestration",
        "orchestrator",
        "handoff",
        "registry",
        "contract",
        "tool handler",
        "bootstrap",
        "provider handshake",
        "preflight",
        "autopilot",
        "scheduler",
        "self-heal",
        "self heal",
        "solo dev",
        "assistant runtime",
        "dev assistant",
        "planner",
    ),
    "dispatch": ("dispatch", "matching", "match", "senderr location", "accept job"),
    "job_board": ("job board", "available jobs", "job list", "view available jobs"),
    "tracking": ("tracking", "location", "start job", "complete job", "status"),
    "pricing": ("pricing", "fare", "surge", "quote", "heatmap", "demand"),
    "reputation": ("rating", "reputation", "review", "score"),
    "payments": ("payment", "wallet", "network pool", "payout", "capture"),
}

DOMAIN_PRIORITY_ORDER = {
    "assistant_runtime": 70,
    "dispatch": 60,
    "job_board": 55,
    "tracking": 50,
    "pricing": 45,
    "reputation": 35,
    "payments": 30,
}

DOMAIN_TERM_EXPANSIONS = {
    "assistant_runtime": (
        "assistant",
        "runtime",
        "permission",
        "permissions",
        "approval",
        "policy",
        "write",
        "gate",
        "confidence",
        "validation",
        "repair",
        "retry",
        "fingerprint",
        "orchestration",
        "orchestrator",
        "handoff",
        "registry",
        "contract",
        "bootstrap",
        "provider",
        "preflight",
        "tool",
        "handler",
        "autopilot",
        "scheduler",
        "planner",
        "artifact",
        "dashboard",
    ),
    "dispatch": ("dispatch", "matching", "match", "worker", "queue", "task", "background", "redis"),
    "job_board": ("job", "board", "listing", "available"),
    "tracking": ("tracking", "location", "status", "progress"),
    "pricing": ("pricing", "price", "fare", "surge", "heatmap", "demand"),
    "reputation": ("rating", "review", "reputation", "score"),
    "payments": ("payment", "wallet", "payout", "ledger", "capture"),
}

SKILLPACK_DEFAULTS = {
    "assistant_runtime": {
        "summary": "Assistant runtime work should stay in the agent runtime, validation, repair, scheduler, desktop host, and VS Code extension paths.",
        "keywords": ["assistant", "runtime", "permission", "approval", "policy", "write gate", "confidence", "validation", "repair", "retry", "fingerprint", "orchestration", "orchestrator", "handoff", "registry", "contract", "bootstrap", "provider", "preflight", "tool", "handler", "autopilot", "scheduler", "planner"],
        "preferred_paths": [
            "backend/agent/core",
            "backend/agent/runtime",
            "backend/agent/agents",
            "backend/tests",
            "backend/scripts",
            "core",
            "shared-runtime",
            "shared-ui",
            "host",
            "renderer",
            "runtime/backend",
            "tools/gosenderr-desktop-agent",
            "tools/vscode-dev-assistant-extension",
            "docs/assistant_runs",
        ],
        "verification_focus": ["targeted pytest assistant runtime tests", "desktop/extension smoke when host logic changes"],
    },
    "dispatch": {
        "summary": "Dispatch work should prefer matching, queue, worker, and senderr-availability flows.",
        "keywords": ["dispatch", "matching", "queue", "worker", "redis", "availability", "assignment"],
        "preferred_paths": ["backend/app/services", "backend/app/workers", "backend/tests"],
        "verification_focus": ["compile backend app", "targeted pytest dispatch/matching tests"],
    },
    "job_board": {
        "summary": "Job-board work should focus on available jobs, listing endpoints, and senderr-facing job retrieval.",
        "keywords": ["job", "board", "listing", "available", "feed"],
        "preferred_paths": ["backend/app/api/routes", "backend/app/services", "frontend/apps/senderr-app"],
        "verification_focus": ["backend route compile", "frontend workspace typecheck when UI is touched"],
    },
    "tracking": {
        "summary": "Tracking changes should preserve job lifecycle and location/status updates.",
        "keywords": ["tracking", "location", "status", "progress", "lifecycle"],
        "preferred_paths": ["backend/app/services", "backend/app/api/routes", "frontend/apps/customer-app", "frontend/apps/senderr-app"],
        "verification_focus": ["compile backend app", "frontend workspace typecheck when UI is touched"],
    },
    "pricing": {
        "summary": "Pricing work should stay scoped to fare, quote, surge, and demand logic.",
        "keywords": ["pricing", "price", "fare", "surge", "quote", "demand", "heatmap"],
        "preferred_paths": ["backend/app/services", "backend/tests", "docs"],
        "verification_focus": ["compile backend app", "targeted pytest pricing tests"],
    },
    "reputation": {
        "summary": "Reputation work should focus on ratings, reviews, and score aggregation.",
        "keywords": ["rating", "review", "reputation", "score"],
        "preferred_paths": ["backend/app/services", "backend/app/models", "backend/tests"],
        "verification_focus": ["compile backend app", "targeted pytest reputation tests"],
    },
    "payments": {
        "summary": "Payments work should preserve wallet balances, capture flows, and GoSenderr Network Pool consistency.",
        "keywords": ["payment", "wallet", "capture", "payout", "network pool", "ledger"],
        "preferred_paths": ["backend/app/services", "backend/app/models", "backend/tests"],
        "verification_focus": ["compile backend app", "targeted pytest payments tests"],
    },
}

SAFE_BLOCKED_TAGS_DEFAULT = {"SEC", "AUTH", "PAYMENT", "MIGRATION", "WALLET"}
SAFE_BLOCKED_DOMAINS_DEFAULT = {"payments"}
SAFE_BLOCKED_TERMS_DEFAULT = ("auth", "payment", "wallet", "network pool", "security", "migration")

DOMAIN_NEGATIVE_TERMS = {
    "assistant_runtime": {"dispatch", "matching", "surge", "wallet", "reputation", "payment"},
    "dispatch": {"pricing", "surge", "fare", "heatmap", "demand"},
    "pricing": {"dispatch", "matching", "queue", "worker", "redis"},
    "payments": {"dispatch", "matching", "surge", "heatmap"},
}

GENERIC_BACKEND_TERMS = {
    "backend",
    "service",
    "services",
    "model",
    "models",
    "route",
    "routes",
    "api",
    "deploy",
    "move",
    "implementation",
    "feature",
    "system",
    "module",
}

STOPWORDS = {
    "add",
    "and",
    "api",
    "apps",
    "auto",
    "backend",
    "based",
    "board",
    "build",
    "customer",
    "data",
    "done",
    "feature",
    "for",
    "from",
    "frontend",
    "have",
    "into",
    "list",
    "model",
    "new",
    "only",
    "portal",
    "route",
    "senderr",
    "support",
    "system",
    "task",
    "tests",
    "the",
    "this",
    "todo",
    "with",
}
